services:
  fontend:
    container_name: frontend
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - smartfood-network

  backend-api:
    container_name: backend-api
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - smartfood-network

networks:
  smartfood-network:
    driver: bridge
