version: '3.8'

services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .next:/app/.next
      - ./public:/app/public
